version: "3.9"

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  producer:
    build: .
    command: node producer.js
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379

  worker-type1:
    build: .
    command: node worker-type1.js
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379

  worker-type2:
    build: .
    command: node worker-type2.js
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379
