version: "3.9"

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  producer:
    build: .
    command: npm run producer
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379

  worker:
    build: .
    command: npm run start
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379
